# Agent Session Replay · distribution-kit macOS lane config (see saagpatel/distribution-kit)
DK_PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DK_PRODUCT_NAME="Agent Session Replay"
DK_BUNDLE_ID="dev.localfirst.agentsessionreplay"
DK_VERSION="0.1.1"
DK_BUILD_CMD="pnpm tauri build"
DK_APP_PATH="$DK_PROJECT_DIR/src-tauri/target/release/bundle/macos/Agent Session Replay.app"
DK_DMG_PATH="$DK_PROJECT_DIR/src-tauri/target/release/bundle/dmg/Agent Session Replay_0.1.1_aarch64.dmg"
DK_SIGNING_IDENTITY="Developer ID Application: SAAGAR I PATEL (3TGZFKFNA4)"
DK_NOTARY_KEY_ID="6NPVH55ZWG"
DK_NOTARY_ISSUER_SERVICE="asc-radar"
DK_NOTARY_ISSUER_ACCOUNT="issuer_id"
DK_CHANNEL="github-release"
DK_GITHUB_REPO="saagpatel/agent-session-replay"
DK_TAG="v0.1.1"
DK_RELEASE_TITLE="Agent Session Replay 0.1.1"
DK_RELEASE_NOTES_FILE="$DK_PROJECT_DIR/RELEASE-NOTES-0.1.1.md"
